# permissions for end users to edit projecttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projecttemplate-editor-role
rules:
- apiGroups:
  - p6s.logan.kiwi
  resources:
  - projecttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - p6s.logan.kiwi
  resources:
  - projecttemplates/status
  verbs:
  - get
