apiVersion: p6s.logan.kiwi/v1alpha1
kind: ProjectTemplate
metadata:
  name: default
  namespace: p6s-system
spec:
  # Add fields here
  resources: |
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app: helloer
        name: helloer-sample
      name: helloer-sample
      namespace: foo
    spec:
      containers:
      - env:
        - name: MESSAGE
          value: Hello world
        image: logie/echoer:latest
        imagePullPolicy: Always
        name: helloer-sample
        ports:
        - containerPort: 9090
          name: echoer
          protocol: TCP
        resources: {}
